{% set name = "gospel" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kortschak/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7182847bc3436923048a50d55eba663d677d06e1901b74f2272db80680b36814

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ stdlib('c') }}
    - go-licenses
    - pkg-config
  host:
    - hunspell
  run:
    - hunspell

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/kortschak/{{ name }}
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - license-files/
  summary: misspelled word linter for Go comments, string literals and embedded files
  dev_url: https://github.com/kortschak/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
